"""empty message

Revision ID: 8a26ae40e2f3
Revises: 7cdc76e3ece7
Create Date: 2023-03-11 23:45:22.398443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a26ae40e2f3'
down_revision = '7cdc76e3ece7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_genre')
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['title'])
        batch_op.drop_constraint('book_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'genre', ['genre_id'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_ibfk_1', 'author', ['author'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('genre_id')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('book_genre',
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='book_genre_ibfk_1'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='book_genre_ibfk_2'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
