version: "3.9"

services:
  db:
    image: mysql:8.0.32-debian
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  db-test:
    image: mysql:8.0.32-debian
    container_name: mysql-test
    environment:
      - MYSQL_DATABASE=${TEST_DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_TEST_PORT}:${DB_PORT}"

  app:
    build:
      context: .
      args:
        - DEV=${DEV}
    environment:
      - DEV=${DEV}
      - SECRET_KEY=${SECRET_KEY}
      - DB=${DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_TEST_PORT=${DB_TEST_PORT}
      - DB_NAME=${DB_NAME}
      - TEST_DB_NAME=${TEST_DB_NAME}
      - COVERAGE_FILE=${COVERAGE_FILE}
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app-user/book-catalog/app
      - coverage:/home/app-user/book-catalog/coverage
    command: >
      sh -c "./app/wait_for_db.sh && flask run --host=0.0.0.0"
    depends_on:
      - db
      - db-test

volumes:
  mysql_data:
  coverage:
